### PR TITLE
Implement avahi/mdns discovery

### PR DESCRIPTION
**Pull request by josephroberts**
Change-type: major

Implement avahi/mdns discovery, this removes the `nmap` dependency and fixes an issue where every so often `nmap` would fail to find dependent devices causing them to be marked as offline

### CODE REVIEW

**Comment by josephroberts** [comment]
@mccollam this is meant to be used on the hotspot network running on the gateway device. We could have an env var to let the user fall back to nmap if they needed to for whatever reason?

**Comment by mccollam** [comment]
Seems like it is a "nice to have" rather than strictly necessary.  I suspect we'll hit Avahi being blocked in the same environment that you're working on this fix for :)  But we can certainly try this out and see.

**Comment by josephroberts** [comment]
@mccollam avahi won't be blocked as the hotspot network is running the rpi... or am I missing something here?

I will add the nmap scan back in as an option.

**Comment by mccollam** [comment]
Ah, good point... you're right.  Not sure nmap is needed then tbh.

**Pull request merged**
