### PR TITLE
Add more ignores to .gitignore

### PR DESCRIPTION
**Pull request by brownjohnf**
Change-Type: Patch

### CODE REVIEW

**Comment by brownjohnf** [comment]
Am I missing something here? @hedss, any reason why this wouldn't merge?

**Comment by hedss** [comment]
@brownjohnf OK, this is very odd. Looking into it, as for some reason it's refusing to merge this PR.

**Comment by hedss** [comment]
@brownjohnf Found it; out of date `versionist` file. Your `Patch` has an upper case character. This has been fixed in the default config, but this file also needs replacing. Am going to submit a PR for it.

**Comment by hedss** [comment]
@brownjohnf Done!

**Comment by brownjohnf** [comment]
Sweet!

**Pull request merged**
